### ISSUE TITLE
Value Error while using merge_output

### ISSUE THREAD

**Issue by stsmall** [FePhyFoFum/quartetsampling#11]
Hi,
I ran quartet_sampling.py on 1500 gene alignments using a fixed topology. I then wanted to merge the output statistics to display the topology with the QS statistics. When I run the merge_output.py it returns an error. Using python 3.6 in Linux with RAxML

 python merge_output.py -d stats.in -t ../quartet_stats_fixtopo/X.astral.root.tre -o ../qs_results                                                            
reading tree from ../quartet_stats_fixtopo/X.astral.root.tre
Traceback (most recent call last):
  File "merge_output.py", line 160, in <module>
    main()
  File "merge_output.py", line 112, in main
    float(arr[qfindex]) * float(arr[repindex]))
ValueError: could not convert string to float: 'qf'

**Example RESULTS.csv**
node_label,freq0,qc,qd,qi,qf,qdsig,diff,num_replicates,notes
QS2,0.13043478260869565,-0.4413706265478008,0.0,0.45999999999999996,NA,NA,3.411908999998559,100,
QS3,1.0,1,NA,1.0,NA,NA,74.57948099999885,100,
QS4,0.3333333333333333,-0.08170416594551044,0.0,0.9,NA,NA,20.70216199999959,100,
QS5,0.39436619718309857,0.008768295340814136,0.9302325581395349,0.71,NA,NA,9.818805000000793,100,
QS6,0.0,-0.022998760578143873,0.821917808219178,0.73,NA,NA,1.0398889999996754,100,
QS7,0.4074074074074074,-0.024880935059134024,0.0,0.81,NA,NA,3.3660729999992327,100,
QS8,0.9722222222222222,0.8168779316986272,0.0,0.9473684210526316,NA,NA,13.666723000000275,76,
QS9,0.07142857142857142,-0.536563217675333,0.15384615384615385,0.3589743589743589,NA,NA,0.5557170000010956,39,
QS10,0.9479166666666666,0.7048182569092414,0.0,0.96,NA,NA,57.657492000000275,100,
QS11,1.0,1,NA,1.0,NA,NA,169.34024300000056,100,
QS12,0.0,-0.4083272214176725,0.2857142857142857,0.3589743589743589,NA,NA,2.345502000000124,39,
QS13,1.0,1,NA,1.0,NA,NA,178.77474799999982,100,
QS14,0.8888888888888888,0.49674166522435426,0.0,0.81,NA,NA,8.904238000000987,100,
QS15,0.025974025974025976,-0.7414574742538906,0.07999999999999996,0.77,NA,NA,2.113827000001038,100,
QS16,0.9565217391304348,0.8149535837823457,0.5,0.92,NA,NA,0.14998299999933806,100,
QS17,0.07692307692307693,-0.6087564363707443,0.0,0.91,NA,NA,22.573661000000357,100,
QS18,0.4186046511627907,-0.16687486814801544,0.28,0.86,NA,NA,7.000949000001128,100,
QS19,0.9587628865979382,0.8224622944620915,0.5,0.97,NA,NA,77.58739500000047,100,
QS20,0.0,-1,0.0,1.0,NA,NA,67.0693510000001,100,
QS21,0.9693877551020408,0.8025469956154399,0.0,0.98,NA,NA,60.483838000000105,100,
QS22,0.7878787878787878,0.25448215718917133,0.0,0.99,NA,NA,69.16358299999956,100,
QS23,0.2857142857142857,-0.136879431433369,0.0,0.98,NA,NA,16.624676999999792,100,
QS24,0.32222222222222224,-0.12199116254109965,0.39344262295081966,0.9,NA,NA,20.406659000000218,100,
QS25,0.05128205128205128,-0.7081817434011142,0.0,1.0,NA,NA,49.264059000001,39,
QS26,1.0,1,NA,1.0,NA,NA,22.98855299999923,100,
QS27,0.96875,0.7993776756872853,0.0,0.96,NA,NA,19.190599999999904,100,
QS28,0.010101010101010102,-0.91853797308494,0.0,0.99,NA,NA,62.95181500000035,100,
QS29,0.97,0.859970988113455,0.6666666666666667,1.0,NA,NA,27.185037999999622,100,
QS30,0.27380952380952384,-0.23013554169084016,0.2295081967213115,0.84,NA,NA,4.468853999998828,100,
QS31,0.047058823529411764,-0.2828777254446335,0.6419753086419753,0.85,NA,NA,10.59984600000098,100,
QS32,0.43548387096774194,-0.31000227641276645,0.05714285714285716,0.8157894736842105,NA,NA,0.042622999999366584,76,
QS33,0.41379310344827586,-0.18939581353164092,0.23529411764705888,0.7435897435897436,NA,NA,4.7718799999984185,39,
QS34,1.0,1,NA,1.0,NA,NA,74.18395699999928,100,
QS35,0.3493975903614458,-0.20442913556422315,0.2222222222222222,0.83,NA,NA,6.3465559999986,100,
QS36,0.35526315789473684,-0.12787178173297276,0.36734693877551017,0.76,NA,NA,2.590110999999524,100,
QS37,0.12790697674418605,-0.5957246291113928,0.026666666666666616,0.86,NA,NA,6.084490999999616,100,
QS38,0.68,0.34585023345983745,0.16666666666666663,0.75,NA,NA,5.614215999999942,100,
QS39,0.8461538461538461,0.5461181928053148,0.33333333333333337,0.513157894736842,NA,NA,2.0646379999998317,76,
QS40,1.0,1,NA,0.4358974358974359,NA,NA,1.8806800000002113,39,
funestus_GhaF264,NA,NA,NA,NA,0.48024316109422494,NA,NA,329.0,
funestus_GhaF265,NA,NA,NA,NA,0.3480825958702065,NA,NA,339.0,
funestus_Ken4590,NA,NA,NA,NA,0.7331189710610932,NA,NA,311.0,
funestus_MozF123,NA,NA,NA,NA,0.44171779141104295,NA,NA,326.0,
funestus_MozF260,NA,NA,NA,NA,0.44155844155844154,NA,NA,385.0,
funestus_MozF29,NA,NA,NA,NA,0.4794520547945205,NA,NA,365.0,
funestus_MozF35,NA,NA,NA,NA,0.5286458333333334,NA,NA,384.0,
funestus_MozF804,NA,NA,NA,NA,0.3949367088607595,NA,NA,395.0,
funestus_TanF561,NA,NA,NA,NA,0.4899713467048711,NA,NA,349.0,
funestus_TanF601,NA,NA,NA,NA,0.5234159779614325,NA,NA,363.0,
funestus_Ugf399,NA,NA,NA,NA,0.4890282131661442,NA,NA,319.0,
funestus_Ugf401,NA,NA,NA,NA,0.4444444444444444,NA,NA,333.0,
funestus_Ugf403,NA,NA,NA,NA,0.603399433427762,NA,NA,353.0,
funestus_Zam281,NA,NA,NA,NA,0.7075718015665796,NA,NA,383.0,
funestuscf_MALAF105_7,NA,NA,NA,NA,0.6782334384858044,NA,NA,317.0,
funestuscf_MALAF99_4,NA,NA,NA,NA,0.6538461538461539,NA,NA,260.0,
funestuscf_MALF98_2,NA,NA,NA,NA,0.6192468619246861,NA,NA,239.0,
longipalpusC_11,NA,NA,NA,NA,0.50920245398773,NA,NA,326.0,
longipalpusC_12,NA,NA,NA,NA,0.33972602739726027,NA,NA,365.0,
longipalpusC_13,NA,NA,NA,NA,0.596100278551532,NA,NA,359.0,
longipalpusC_15,NA,NA,NA,NA,0.41688654353562005,NA,NA,379.0,
longipalpusC_16,NA,NA,NA,NA,0.446064139941691,NA,NA,343.0,
longipalpusC_4,NA,NA,NA,NA,0.5347432024169184,NA,NA,331.0,
longipalpusC_551_12533,NA,NA,NA,NA,0.4169381107491857,NA,NA,307.0,
longipalpusC_551_12634,NA,NA,NA,NA,0.5399361022364217,NA,NA,313.0,
parensis_KwaF761,NA,NA,NA,NA,0.5161290322580645,NA,NA,310.0,
parensis_KwaF762,NA,NA,NA,NA,0.4502923976608187,NA,NA,342.0,
parensis_KwaF766,NA,NA,NA,NA,0.36944444444444446,NA,NA,360.0,
parensis_KwaF767,NA,NA,NA,NA,0.5033333333333333,NA,NA,300.0,
parensis_KwaF768,NA,NA,NA,NA,0.4955223880597015,NA,NA,335.0,
parensis_KwaF769,NA,NA,NA,NA,0.49066666666666664,NA,NA,375.0,
parensis_KwaF835,NA,NA,NA,NA,0.4408284023668639,NA,NA,338.0,
parensis_KwaF851,NA,NA,NA,NA,0.4527687296416938,NA,NA,307.0,
rivulorum_F790,NA,NA,NA,NA,0.45454545454545453,NA,NA,297.0,
vaneedeni_KwaF773,NA,NA,NA,NA,0.5070821529745042,NA,NA,353.0,
vaneedeni_KwaF774,NA,NA,NA,NA,0.44036697247706424,NA,NA,327.0,
vaneedeni_KwaF775,NA,NA,NA,NA,0.5283582089552239,NA,NA,335.0,
vaneedeni_KwaF780,NA,NA,NA,NA,0.3135593220338983,NA,NA,354.0,
vaneedeni_KwaF782,NA,NA,NA,NA,0.5110410094637224,NA,NA,317.0,
vaneedeni_KwaF783,NA,NA,NA,NA,0.3379501385041551,NA,NA,361.0,
vaneedeni_KwaF784,NA,NA,NA,NA,0.41368078175895767,NA,NA,307.0,
vaneedeni_KwaF786,NA,NA,NA,NA,0.46511627906976744,NA,NA,301.0,

**Comment by jbpease** [comment]
This was a bug where the detection of headers did not reset for the section file.  Should work now.  Thanks for catching this.
