### ISSUE TITLE
self['temp_wd'] will fail if no default setting given

### ISSUE THREAD

**Issue by SimonGreenhill** [FePhyFoFum/quartetsampling#3]
If run without `-e TEMP_DIR` the parameter `self['temp_wd']` is set to `/` (i.e. the root directory). This will then fail with the difficult to debug error because most users can't (and should not) be able to write to the root directory:

```
Traceback (most recent call last):
  File "quartet_sampling.py", line 304, in <module>
    main()
  File "quartet_sampling.py", line 214, in main
    write_test_trees()
  File ".../quartetsampling/pysrc/tree_data.py", line 369, in write_test_trees
    with open(out, "w") as xtrees:
PermissionError: [Errno 13] Permission denied: 'test.trees.0'
```

quartetsampling should either check that `temp_wd` is writeable and raise a helpful error message, or use the temporary directory capabilities in [tempfile.mkdtemp](https://docs.python.org/3.6/library/tempfile.html)

**Comment by SimonGreenhill** [comment]
Yikes, and `quartetsampling` tries, on exit, to remove the directory specified as the temp_dir. If this is set to / and the users have write permissions there, they're in for a world of pain. 

This also suggests using tempfile.mkdtemp is a better idea. I naively set `-e /tmp` and `quartetsampling` crashes when trying to remove all my files in `/tmp`, which it can't do because some (not owned by quartetsampling) are still being written to. Using tempfile.mkdtemp means that you can delete the directory without killing any of my files, and avoids the glitch.

**Comment by jbpease** [comment]
Thanks for finding this.  It should now default to ./QuartetSampling.  I have also implemented that now the temporary directory must include "QuartetSampling" in the name and the final removal step will check the absolute path to make sure the characters "QuartetSampling" appears in the file path.  Let me know if you still have issues with this.
