### ISSUE TITLE
Enable binary/discrete data

### ISSUE THREAD

**Issue by SimonGreenhill** [FePhyFoFum/quartetsampling#5]
PAUP* can handle binary/discrete data with the MKv model. 

This can be added easily if the nexus file output is set to `datatype=standard` rather than `datatype=dna`, and '0123456789' is added to [valid_chars](https://github.com/FePhyFoFum/quartetsampling/blob/master/pysrc/alignment.py#L39). 

There's currently a flag `amino_acid` controlling DNA vs Amino Acid datatypes, but perhaps a better method would be to have a `datatype` = {dna (default), amino_acid, binary} flag?

**Comment by jbpease** [comment]
This has been added, the -A/--amino-acid flag is now -d/--data-type with a "cat" option that will invoke paup categorical mode and allow 0-9,A-Z,a-z as characters.  Let me know if this does not work for your files.

**Comment by SimonGreenhill** [comment]
Almost, thanks! The check for paup mode needs to come after the mode is identified and PAUP expects datatype=standard. The PR in #6 should fix these issues.

**Comment by jbpease** [comment]
Thanks for this.  PR#6 merged.
