### ISSUE TITLE
Error when processing second node

### ISSUE THREAD

**Issue by kcart7** [FePhyFoFum/quartetsampling#7]
Hello, 

I'm getting the following error when trying to run quartetsampling:

processing node 1/91
not calculating qc for tip child '26fullgene' of the root (qc is 1.0, as for all tips).

processing node 2/91 | average node time 0.01 seconds | est. remaining time 1.30 seconds
Traceback (most recent call last):
  File "/raid1/home/bpp/home/local/bin/quartetsampling/pysrc/quartet_sampling.py", line 318, in <module>
    main()
  File "/raid1/home/bpp/home/local/bin/quartetsampling/pysrc/quartet_sampling.py", line 273, in main
    elif params['lnlikethresh'] > 0:
TypeError: unorderable types: list() > int()

Here's the command I'm using as well:
python3.5 /raid1/home/bpp/home/local/bin/quartetsampling/pysrc/quartet_sampling.py -t tree.tre -a alignment.phyml -N 100 -T 1 -L 2 -g gene_partition_file.txt --ignore-errors

Thanks for the help! Looking forward to using this program.

**Comment by jbpease** [comment]
Thanks for finding this and sending a full error message!
This bug has been fixed, please "git pull" the latest version and try it again.

Feel free to contact us again if you have any more issues.

James

**Comment by kcart7** [comment]
Thanks for the quick response!
